### ISSUE TITLE
Auth Endpoint Exposed

### ISSUE THREAD

**Issue by jacobwise** [vamsii777/directus-extension-bundle-firebase-main#3]
Couldn't anyone with the uid of the firebase user authenticate to the directus backend?

**Comment by vamsii777** [comment]
Hey there! If you're worried about the security of using Firebase UIDs with Directus, here's some good news. The extension requires a valid Firebase ID token, which gets a thorough check-up with the Firebase Admin SDK to make sure it's legit. This means only users with an actual Firebase session can hop into Directus. 

Plus, for an extra layer of coziness, it creates a one-time token that's only good for a short while. So, rest easy knowing there's a solid security setup in place!

**Comment by jacobwise** [comment]
I'm looking at [handleTokenAuthRequest](https://github.com/vamsii777/directus-extension-bundle-firebase/blob/main/src/firebase-connect/index.ts). It doesn't appear to check the Firebase ID token before it creates the directus token.

**Comment by vamsii777** [comment]
A Directus session is generated only if there exists a user with an external identifier that matches the Firebase UID, thereby ensuring a secure linkage. Conversely, should there be no user corresponding to the Firebase UID within the external identifiers, it would throw an error.

**Comment by jacobwise** [comment]
I'm looking at the `/auth` endpoint, there is no check on that endpoint for a valid token.

             async function handleTokenAuthRequest(req: any, res: any) {
			try {
				const { AuthenticationService } = services;
				const userId = req.body.uid;
		                 let user = await database('directus_users').where({ external_identifier: userId }).first();
		
				// Create one time session token (OTST) with 30s lifetime
				const otst = nanoid(64);
				const expiration = addSeconds(new Date(), 30);
		
				await database.insert({
				  token: otst,
				  user: user.id,
				  expires: expiration,
				  ip: req.ip,
				  user_agent: req.get('user-agent')
				}).into('directus_sessions');
		
				// Try to authenticate by refreshing (OTST)
				const accountability = {
				  ip: req.ip,
				  userAgent: req.get('user-agent'),
				  role: user.role,
				};
		
				const authenticationService = new AuthenticationService({
				  accountability: accountability,
				  schema: await getSchema(),
				});
		
				logger.debug(`Generated tokens for user ID: ${user.id}`);
		
				const { accessToken, refreshToken, expires } = await authenticationService.refresh(otst);
		
				const data = {
				  access_token: accessToken,
				  refresh_token: refreshToken,
				  expires
				};
		
				res.json({data});
		
			  } catch (error) {
				logger.error(`Error generating token: ${error}`, error);
				return res.status(500).json({ error: error });
			  }
		}

**Comment by vamsii777** [comment]
Typically, the process involves creating a Directus user associated with a Firebase ID Token. Following this, the Firebase UID is utilized to obtain a Directus access token, granting the capability to access Directus items securely.

**Comment by jacobwise** [comment]
Okay, so what I'm saying is if I had a valid firebase uid, I could authenticate to the directus backend without a valid token.

**Comment by vamsii777** [comment]
In order to authenticate, the user must already exist within Directus. In the authentication process checks if the provided Firebase UID matches an existing user in Directus, identified by the `external_identifier` field. Here's a snippet illustrating this check:

```javascript
const userId = req.body.uid; // The Firebase UID provided in the request

// Attempt to find a Directus user with a matching external_identifier
let user = await database('directus_users').where({ external_identifier: userId }).first();
```

If a user in Directus matches the given Firebase UID, then it will proceed to authenticate the user and return a token. If no matching user is found, an error will be generated, indicating the authentication process cannot proceed.

If you are looking to enhance authentication mechanism by incorporating Firebase UID validation directly through the Firebase Admin SDK. Below is an example function that checks whether a Firebase UID corresponds to an existing Firebase user. This could be a starting point for integrating such validation into the extenstion:

```javascript 
async function firebaseCheckUserExistsByUID(uid) {
  try {
    // Attempts to retrieve the Firebase user based on the provided UID
    await admin.auth().getUser(uid);
    // If successful, it means the Firebase user exists
    return { exists: true };
  } catch (error) {
    if (error.code === 'auth/user-not-found') {
      // Specifically catches the case where a Firebase user does not exist
      return { exists: false };
    } else {
      // Logs any other errors encountered during the existence check
      console.error('Error checking user existence:', error);
      throw error; // Rethrows the error for further handling
    }
  }
}
```

If you're interested in helping or improving the integration with Firebase, I suggest you to submit a Pull Request with your proposed validation logic.

**Comment by jacobwise** [comment]
Will do! Just wanted to make sure I wasn't missing something here.
